{% set name = "pennylane-qchem" %}
{% set version = "0.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PennyLane-Qchem-{{ version }}.tar.gz
  sha256: 52e2416bb51772ff8e33229f5391b4b600b997468b5ba395322c47d05fcaf864

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - h5py <=3.2.1
    - openfermion >=1.0
    - openfermionpsi4 >=0.5
    - openfermionpyscf >=0.5
    - pennylane >=0.13
    - pyscf >=1.7.2
    - python >=3.5
    - scipy

test:
  imports:
    - pennylane_qchem
    - pennylane_qchem.qchem
  commands:
    - pip check
  requires:
    - pip


about:
  home: http://xanadu.ai
  summary: Package for quantum chemistry applications
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pennylane.readthedocs.io/en/stable/introduction/chemistry.html
  dev_url: https://github.com/PennyLaneAI/pennylane/tree/master/qchem

extra:
  recipe-maintainers:
    - BastianZim
